/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetDoors200,
  GetDoorsControllerIdAccessLogs200,
  GetDoorsControllerIdAccessLogsParams,
  GetDoorsControllerIdCommands200,
  GetDoorsControllerIdCommandsParams,
  GetIotDevicesControllerIdCommands200,
  GetIotDevicesControllerIdCommandsParams,
  GetLogs200,
  GetLogsParams,
  GetRooms200,
  GetRoomsIdAccessLogs200,
  GetRoomsIdAccessLogsParams,
  GetRoomsIdRelations200,
  GetRoomsParams,
  GetRoomsSummary200,
  GetRoomsSummaryParams,
  GetUsers200,
  GetUsersIdFingerprints200Item,
  GetUsersIdNfcTags200Item,
  GetUsersIdRelations200,
  GetUsersMe200,
  GetUsersParams,
  PatchIotDevicesControllerIdCommandsCommandIdAck200,
  PatchIotDevicesControllerIdCommandsCommandIdAckBody,
  PatchIotDevicesControllerIdHeartbeat200,
  PatchIotDevicesControllerIdHeartbeatBody,
  PatchUsersIdFingerprintsCredentialId200,
  PatchUsersIdFingerprintsCredentialIdBody,
  PatchUsersIdNfcTagsCredentialId200,
  PatchUsersIdNfcTagsCredentialIdBody,
  PostDoorsControllerIdCommands201,
  PostDoorsControllerIdCommandsBody,
  PostIotDevicesControllerIdAccessAttempts200,
  PostIotDevicesControllerIdAccessAttemptsBody,
  PostIotDevicesControllerIdCommands201,
  PostIotDevicesControllerIdCommandsBody,
  PostIotDevicesControllerIdEnrollment201,
  PostIotDevicesControllerIdEnrollmentBody,
  PostRooms201,
  PostRoomsBody,
  PostRoomsIdProfilesBody,
  PostRoomsIdProfilesBulkBody,
  PostRoomsIdUsers201,
  PostRoomsIdUsersBody,
  PostRoomsIdUsersBulkBody,
  PostUsers201,
  PostUsersBody,
  PostUsersIdFingerprints201,
  PostUsersIdFingerprintsBody,
  PostUsersIdNfcTags201,
  PostUsersIdNfcTagsBody,
  PutIotDevicesControllerId200,
  PutIotDevicesControllerIdBody,
  PutIotDevicesControllerIdStatus200,
  PutIotDevicesControllerIdStatusBody,
  PutRoomsId200,
  PutRoomsIdBody,
  PutUsersId200,
  PutUsersIdBody
} from './schemas';

import { mutator } from './mutator';
export const getAccessControlAPI = () => {
/**
 * Retorna os dados do usuário logado, incluindo se é administrador.
 * @summary Dados do usuário autenticado
 */
const getUsersMe = (
    
 ) => {
      return mutator<GetUsersMe200>(
      {url: `/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * Retorna os usuários cadastrados e indica se possuem credencial física associada.
 * @summary Listar usuários
 */
const getUsers = (
    params?: GetUsersParams,
 ) => {
      return mutator<GetUsers200>(
      {url: `/users/`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Cria um novo usuário no sistema. Opcionalmente vincula perfis, salas e tipos de sala.
 * @summary Criar usuário
 */
const postUsers = (
    postUsersBody: PostUsersBody,
 ) => {
      return mutator<PostUsers201>(
      {url: `/users/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postUsersBody
    },
      );
    }
  
/**
 * Retorna as impressões digitais cadastradas para um usuário.
 * @summary Listar digitais do usuário
 */
const getUsersIdFingerprints = (
    id: string,
 ) => {
      return mutator<GetUsersIdFingerprints200Item[]>(
      {url: `/users/${id}/fingerprints`, method: 'GET'
    },
      );
    }
  
/**
 * Registra uma nova impressão digital para o usuário. Máximo de 1 por dedo.
 * @summary Cadastrar digital
 */
const postUsersIdFingerprints = (
    id: string,
    postUsersIdFingerprintsBody: PostUsersIdFingerprintsBody,
 ) => {
      return mutator<PostUsersIdFingerprints201>(
      {url: `/users/${id}/fingerprints`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postUsersIdFingerprintsBody
    },
      );
    }
  
/**
 * Remove uma impressão digital cadastrada do usuário.
 * @summary Remover digital
 */
const deleteUsersIdFingerprintsCredentialId = (
    id: string,
    credentialId: string,
 ) => {
      return mutator<unknown>(
      {url: `/users/${id}/fingerprints/${credentialId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Alterna o status ativo/inativo de uma impressão digital.
 * @summary Ativar/desativar digital
 */
const patchUsersIdFingerprintsCredentialId = (
    id: string,
    credentialId: string,
    patchUsersIdFingerprintsCredentialIdBody: PatchUsersIdFingerprintsCredentialIdBody,
 ) => {
      return mutator<PatchUsersIdFingerprintsCredentialId200>(
      {url: `/users/${id}/fingerprints/${credentialId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchUsersIdFingerprintsCredentialIdBody
    },
      );
    }
  
/**
 * Retorna as os cartões NFC cadastradas para um usuário.
 * @summary Listar cartões NFC do usuário
 */
const getUsersIdNfcTags = (
    id: string,
 ) => {
      return mutator<GetUsersIdNfcTags200Item[]>(
      {url: `/users/${id}/nfc-tags`, method: 'GET'
    },
      );
    }
  
/**
 * Registra uma nova cartão NFC para o usuário. Apenas cartões únicos.
 * @summary Cadastrar cartão NFC
 */
const postUsersIdNfcTags = (
    id: string,
    postUsersIdNfcTagsBody: PostUsersIdNfcTagsBody,
 ) => {
      return mutator<PostUsersIdNfcTags201>(
      {url: `/users/${id}/nfc-tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postUsersIdNfcTagsBody
    },
      );
    }
  
/**
 * Remove uma cartão NFC cadastrada do usuário.
 * @summary Remover cartão NFC
 */
const deleteUsersIdNfcTagsCredentialId = (
    id: string,
    credentialId: string,
 ) => {
      return mutator<unknown>(
      {url: `/users/${id}/nfc-tags/${credentialId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Alterna o status ativo/inativo de uma cartão NFC.
 * @summary Ativar/desativar cartão NFC
 */
const patchUsersIdNfcTagsCredentialId = (
    id: string,
    credentialId: string,
    patchUsersIdNfcTagsCredentialIdBody: PatchUsersIdNfcTagsCredentialIdBody,
 ) => {
      return mutator<PatchUsersIdNfcTagsCredentialId200>(
      {url: `/users/${id}/nfc-tags/${credentialId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchUsersIdNfcTagsCredentialIdBody
    },
      );
    }
  
/**
 * Retorna os perfis, salas e tipos de sala associados ao usuário.
 * @summary Vínculos do usuário
 */
const getUsersIdRelations = (
    id: string,
 ) => {
      return mutator<GetUsersIdRelations200>(
      {url: `/users/${id}/relations`, method: 'GET'
    },
      );
    }
  
/**
 * Atualiza os dados de um usuário e sincroniza perfis, salas e tipos de sala.
 * @summary Atualizar usuário
 */
const putUsersId = (
    id: string,
    putUsersIdBody: PutUsersIdBody,
 ) => {
      return mutator<PutUsersId200>(
      {url: `/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUsersIdBody
    },
      );
    }
  
/**
 * Remove um usuário do sistema.
 * @summary Excluir usuário
 */
const deleteUsersId = (
    id: string,
 ) => {
      return mutator<unknown>(
      {url: `/users/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Retorna os logs de acesso paginados com suporte a filtros.
 * @summary Listar logs de acesso
 */
const getLogs = (
    params?: GetLogsParams,
 ) => {
      return mutator<GetLogs200>(
      {url: `/logs/`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Abre uma conexão Server-Sent Events. O servidor emite um evento `room-status` sempre que o estado de uma sala é atualizado pelo controlador IoT.
 * @summary Stream de eventos de status das salas (SSE)
 */
const getRoomsEvents = (
    
 ) => {
      return mutator<unknown>(
      {url: `/rooms/events`, method: 'GET'
    },
      );
    }
  
/**
 * Retorna todas as salas agrupadas por bloco com nome, tipo, estado e horário da última atualização. Se o chamador estiver autenticado, inclui também quem está usando a sala no momento e quem foi o último utilizador.
 * @summary Resumo de salas agrupadas por bloco
 */
const getRoomsSummary = (
    params?: GetRoomsSummaryParams,
 ) => {
      return mutator<GetRoomsSummary200>(
      {url: `/rooms/summary`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Retorna as salas cadastradas, incluindo estado atual da porta e informações do bloco.
 * @summary Listar salas e blocos
 */
const getRooms = (
    params?: GetRoomsParams,
 ) => {
      return mutator<GetRooms200>(
      {url: `/rooms/`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Cria uma nova sala. Opcionalmente vincula perfis e usuários com acesso direto.
 * @summary Criar sala
 */
const postRooms = (
    postRoomsBody: PostRoomsBody,
 ) => {
      return mutator<PostRooms201>(
      {url: `/rooms/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRoomsBody
    },
      );
    }
  
/**
 * Retorna os perfis e usuários com acesso direto associados à sala.
 * @summary Vínculos da sala
 */
const getRoomsIdRelations = (
    id: string,
 ) => {
      return mutator<GetRoomsIdRelations200>(
      {url: `/rooms/${id}/relations`, method: 'GET'
    },
      );
    }
  
/**
 * Atualiza os dados de uma sala e sincroniza perfis e usuários com acesso direto.
 * @summary Atualizar sala
 */
const putRoomsId = (
    id: string,
    putRoomsIdBody: PutRoomsIdBody,
 ) => {
      return mutator<PutRoomsId200>(
      {url: `/rooms/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putRoomsIdBody
    },
      );
    }
  
/**
 * Remove uma sala do sistema.
 * @summary Excluir sala
 */
const deleteRoomsId = (
    id: string,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Atribuir perfil à sala
 */
const postRoomsIdProfiles = (
    id: string,
    postRoomsIdProfilesBody: PostRoomsIdProfilesBody,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}/profiles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRoomsIdProfilesBody
    },
      );
    }
  
/**
 * @summary Remover perfil da sala
 */
const deleteRoomsIdProfilesProfileId = (
    id: string,
    profileId: string,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}/profiles/${profileId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Atribuir permissão direta de usuário à sala
 */
const postRoomsIdUsers = (
    id: string,
    postRoomsIdUsersBody: PostRoomsIdUsersBody,
 ) => {
      return mutator<PostRoomsIdUsers201>(
      {url: `/rooms/${id}/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRoomsIdUsersBody
    },
      );
    }
  
/**
 * @summary Remover permissão direta de usuário da sala
 */
const deleteRoomsIdUsersUserId = (
    id: string,
    userId: string,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}/users/${userId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Substitui completamente a lista de usuários com permissão direta para a sala.
 * @summary Sincronizar usuários com acesso direto à sala
 */
const postRoomsIdUsersBulk = (
    id: string,
    postRoomsIdUsersBulkBody: PostRoomsIdUsersBulkBody,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}/users/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRoomsIdUsersBulkBody
    },
      );
    }
  
/**
 * Substitui completamente a lista de perfis com permissão para a sala.
 * @summary Sincronizar perfis com acesso à sala
 */
const postRoomsIdProfilesBulk = (
    id: string,
    postRoomsIdProfilesBulkBody: PostRoomsIdProfilesBulkBody,
 ) => {
      return mutator<unknown>(
      {url: `/rooms/${id}/profiles/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRoomsIdProfilesBulkBody
    },
      );
    }
  
/**
 * Retorna os últimos registros de acesso (GRANTED) de uma sala. Requer autenticação de admin.
 * @summary Logs de acesso recentes de uma sala
 */
const getRoomsIdAccessLogs = (
    id: string,
    params?: GetRoomsIdAccessLogsParams,
 ) => {
      return mutator<GetRoomsIdAccessLogs200>(
      {url: `/rooms/${id}/access-logs`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Retorna todos os controladores físicos cadastrados, status atual e último comando enviado.
 * @summary Listar controladores de porta
 */
const getDoors = (
    
 ) => {
      return mutator<GetDoors200>(
      {url: `/doors/`, method: 'GET'
    },
      );
    }
  
/**
 * Consulta os comandos emitidos para um controlador específico.
 * @summary Histórico de comandos
 */
const getDoorsControllerIdCommands = (
    controllerId: string,
    params?: GetDoorsControllerIdCommandsParams,
 ) => {
      return mutator<GetDoorsControllerIdCommands200>(
      {url: `/doors/${controllerId}/commands`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Agenda um novo comando administrativo (trava, destrava, sincronização de estado) para o controlador informado.
 * @summary Enviar comando para controlador
 */
const postDoorsControllerIdCommands = (
    controllerId: string,
    postDoorsControllerIdCommandsBody: PostDoorsControllerIdCommandsBody,
 ) => {
      return mutator<PostDoorsControllerIdCommands201>(
      {url: `/doors/${controllerId}/commands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postDoorsControllerIdCommandsBody
    },
      );
    }
  
/**
 * Retorna o histórico recente de tentativas de acesso registradas para a sala vinculada ao controlador.
 * @summary Consultar logs de acesso
 */
const getDoorsControllerIdAccessLogs = (
    controllerId: string,
    params?: GetDoorsControllerIdAccessLogsParams,
 ) => {
      return mutator<GetDoorsControllerIdAccessLogs200>(
      {url: `/doors/${controllerId}/access-logs`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Usado pelo dispositivo IoT para criar ou atualizar seu cadastro junto à API usando PUT idempotente.
 * @summary Registrar ou atualizar controlador
 */
const putIotDevicesControllerId = (
    controllerId: string,
    putIotDevicesControllerIdBody: PutIotDevicesControllerIdBody,
 ) => {
      return mutator<PutIotDevicesControllerId200>(
      {url: `/iot/devices/${controllerId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putIotDevicesControllerIdBody
    },
      );
    }
  
/**
 * Atualiza o timestamp de últimos sinais de vida do dispositivo e opcionalmente a versão do firmware.
 * @summary Heartbeat do controlador
 */
const patchIotDevicesControllerIdHeartbeat = (
    controllerId: string,
    patchIotDevicesControllerIdHeartbeatBody: PatchIotDevicesControllerIdHeartbeatBody,
 ) => {
      return mutator<PatchIotDevicesControllerIdHeartbeat200>(
      {url: `/iot/devices/${controllerId}/heartbeat`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchIotDevicesControllerIdHeartbeatBody
    },
      );
    }
  
/**
 * Persistir o estado atual detectado pelo controlador (fechada/aberta, trancada/destrancada).
 * @summary Atualizar status da porta
 */
const putIotDevicesControllerIdStatus = (
    controllerId: string,
    putIotDevicesControllerIdStatusBody: PutIotDevicesControllerIdStatusBody,
 ) => {
      return mutator<PutIotDevicesControllerIdStatus200>(
      {url: `/iot/devices/${controllerId}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putIotDevicesControllerIdStatusBody
    },
      );
    }
  
/**
 * Avalia uma credencial apresentada ao controlador e retorna a decisão (permitido ou negado).
 * @summary Registrar tentativa de acesso
 */
const postIotDevicesControllerIdAccessAttempts = (
    controllerId: string,
    postIotDevicesControllerIdAccessAttemptsBody: PostIotDevicesControllerIdAccessAttemptsBody,
 ) => {
      return mutator<PostIotDevicesControllerIdAccessAttempts200>(
      {url: `/iot/devices/${controllerId}/access-attempts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postIotDevicesControllerIdAccessAttemptsBody
    },
      );
    }
  
/**
 * Permite que o controlador solicite um comando imediato (por exemplo, destravar temporariamente a porta).
 * @summary Criar comando emergencial
 */
const postIotDevicesControllerIdCommands = (
    controllerId: string,
    postIotDevicesControllerIdCommandsBody: PostIotDevicesControllerIdCommandsBody,
 ) => {
      return mutator<PostIotDevicesControllerIdCommands201>(
      {url: `/iot/devices/${controllerId}/commands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postIotDevicesControllerIdCommandsBody
    },
      );
    }
  
/**
 * Entrega ao controlador os comandos na fila que ainda não foram enviados ou expirados.
 * @summary Buscar comandos pendentes
 */
const getIotDevicesControllerIdCommands = (
    controllerId: string,
    params?: GetIotDevicesControllerIdCommandsParams,
 ) => {
      return mutator<GetIotDevicesControllerIdCommands200>(
      {url: `/iot/devices/${controllerId}/commands`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Endpoint interno chamado pelo broker MQTT ao processar o resultado de enrollment biométrico capturado por um controlador físico. Não exige cookie de sessão — autenticado pelo controllerId.
 * @summary Registrar digital via terminal de enrollment
 */
const postIotDevicesControllerIdEnrollment = (
    controllerId: string,
    postIotDevicesControllerIdEnrollmentBody: PostIotDevicesControllerIdEnrollmentBody,
 ) => {
      return mutator<PostIotDevicesControllerIdEnrollment201>(
      {url: `/iot/devices/${controllerId}/enrollment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postIotDevicesControllerIdEnrollmentBody
    },
      );
    }
  
/**
 * Atualiza o status de um comando após processamento pelo controlador, incluindo payload de resultado ou erro.
 * @summary Confirmar execução de comando
 */
const patchIotDevicesControllerIdCommandsCommandIdAck = (
    controllerId: string,
    commandId: string,
    patchIotDevicesControllerIdCommandsCommandIdAckBody: PatchIotDevicesControllerIdCommandsCommandIdAckBody,
 ) => {
      return mutator<PatchIotDevicesControllerIdCommandsCommandIdAck200>(
      {url: `/iot/devices/${controllerId}/commands/${commandId}/ack`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchIotDevicesControllerIdCommandsCommandIdAckBody
    },
      );
    }
  
return {getUsersMe,getUsers,postUsers,getUsersIdFingerprints,postUsersIdFingerprints,deleteUsersIdFingerprintsCredentialId,patchUsersIdFingerprintsCredentialId,getUsersIdNfcTags,postUsersIdNfcTags,deleteUsersIdNfcTagsCredentialId,patchUsersIdNfcTagsCredentialId,getUsersIdRelations,putUsersId,deleteUsersId,getLogs,getRoomsEvents,getRoomsSummary,getRooms,postRooms,getRoomsIdRelations,putRoomsId,deleteRoomsId,postRoomsIdProfiles,deleteRoomsIdProfilesProfileId,postRoomsIdUsers,deleteRoomsIdUsersUserId,postRoomsIdUsersBulk,postRoomsIdProfilesBulk,getRoomsIdAccessLogs,getDoors,getDoorsControllerIdCommands,postDoorsControllerIdCommands,getDoorsControllerIdAccessLogs,putIotDevicesControllerId,patchIotDevicesControllerIdHeartbeat,putIotDevicesControllerIdStatus,postIotDevicesControllerIdAccessAttempts,postIotDevicesControllerIdCommands,getIotDevicesControllerIdCommands,postIotDevicesControllerIdEnrollment,patchIotDevicesControllerIdCommandsCommandIdAck}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetUsersMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getUsersMe']>>>
export type GetUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getUsers']>>>
export type PostUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postUsers']>>>
export type GetUsersIdFingerprintsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getUsersIdFingerprints']>>>
export type PostUsersIdFingerprintsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postUsersIdFingerprints']>>>
export type DeleteUsersIdFingerprintsCredentialIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteUsersIdFingerprintsCredentialId']>>>
export type PatchUsersIdFingerprintsCredentialIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['patchUsersIdFingerprintsCredentialId']>>>
export type GetUsersIdNfcTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getUsersIdNfcTags']>>>
export type PostUsersIdNfcTagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postUsersIdNfcTags']>>>
export type DeleteUsersIdNfcTagsCredentialIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteUsersIdNfcTagsCredentialId']>>>
export type PatchUsersIdNfcTagsCredentialIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['patchUsersIdNfcTagsCredentialId']>>>
export type GetUsersIdRelationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getUsersIdRelations']>>>
export type PutUsersIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['putUsersId']>>>
export type DeleteUsersIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteUsersId']>>>
export type GetLogsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getLogs']>>>
export type GetRoomsEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getRoomsEvents']>>>
export type GetRoomsSummaryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getRoomsSummary']>>>
export type GetRoomsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getRooms']>>>
export type PostRoomsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postRooms']>>>
export type GetRoomsIdRelationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getRoomsIdRelations']>>>
export type PutRoomsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['putRoomsId']>>>
export type DeleteRoomsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteRoomsId']>>>
export type PostRoomsIdProfilesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postRoomsIdProfiles']>>>
export type DeleteRoomsIdProfilesProfileIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteRoomsIdProfilesProfileId']>>>
export type PostRoomsIdUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postRoomsIdUsers']>>>
export type DeleteRoomsIdUsersUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['deleteRoomsIdUsersUserId']>>>
export type PostRoomsIdUsersBulkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postRoomsIdUsersBulk']>>>
export type PostRoomsIdProfilesBulkResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postRoomsIdProfilesBulk']>>>
export type GetRoomsIdAccessLogsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getRoomsIdAccessLogs']>>>
export type GetDoorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getDoors']>>>
export type GetDoorsControllerIdCommandsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getDoorsControllerIdCommands']>>>
export type PostDoorsControllerIdCommandsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postDoorsControllerIdCommands']>>>
export type GetDoorsControllerIdAccessLogsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getDoorsControllerIdAccessLogs']>>>
export type PutIotDevicesControllerIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['putIotDevicesControllerId']>>>
export type PatchIotDevicesControllerIdHeartbeatResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['patchIotDevicesControllerIdHeartbeat']>>>
export type PutIotDevicesControllerIdStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['putIotDevicesControllerIdStatus']>>>
export type PostIotDevicesControllerIdAccessAttemptsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postIotDevicesControllerIdAccessAttempts']>>>
export type PostIotDevicesControllerIdCommandsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postIotDevicesControllerIdCommands']>>>
export type GetIotDevicesControllerIdCommandsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['getIotDevicesControllerIdCommands']>>>
export type PostIotDevicesControllerIdEnrollmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['postIotDevicesControllerIdEnrollment']>>>
export type PatchIotDevicesControllerIdCommandsCommandIdAckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccessControlAPI>['patchIotDevicesControllerIdCommandsCommandIdAck']>>>
