/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdCommands404Error = typeof GetDoorsControllerIdCommands404Error[keyof typeof GetDoorsControllerIdCommands404Error];


export const GetDoorsControllerIdCommands404Error = {
  Controller_not_found: 'Controller not found',
} as const;
