/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdCommands200CommandsItemType = typeof GetDoorsControllerIdCommands200CommandsItemType[keyof typeof GetDoorsControllerIdCommands200CommandsItemType];


export const GetDoorsControllerIdCommands200CommandsItemType = {
  UNLOCK: 'UNLOCK',
  LOCK: 'LOCK',
  SYNC_STATE: 'SYNC_STATE',
} as const;
