/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDoorsControllerIdCommands404Code } from './getDoorsControllerIdCommands404Code';
import type { GetDoorsControllerIdCommands404Error } from './getDoorsControllerIdCommands404Error';

export type GetDoorsControllerIdCommands404 = {
  error: GetDoorsControllerIdCommands404Error;
  code: GetDoorsControllerIdCommands404Code;
};
