/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdAccessLogs404Error = typeof GetDoorsControllerIdAccessLogs404Error[keyof typeof GetDoorsControllerIdAccessLogs404Error];


export const GetDoorsControllerIdAccessLogs404Error = {
  Controller_not_found: 'Controller not found',
} as const;
