/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDoors200ControllersItemController } from './getDoors200ControllersItemController';
import type { GetDoors200ControllersItemLastCommand } from './getDoors200ControllersItemLastCommand';
import type { GetDoors200ControllersItemRoom } from './getDoors200ControllersItemRoom';

export type GetDoors200ControllersItem = {
  controllerId: string;
  room: GetDoors200ControllersItemRoom;
  controller: GetDoors200ControllersItemController;
  /** @nullable */
  lastCommand: GetDoors200ControllersItemLastCommand;
};
