/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDoorsControllerIdAccessLogs404Code } from './getDoorsControllerIdAccessLogs404Code';
import type { GetDoorsControllerIdAccessLogs404Error } from './getDoorsControllerIdAccessLogs404Error';

export type GetDoorsControllerIdAccessLogs404 = {
  error: GetDoorsControllerIdAccessLogs404Error;
  code: GetDoorsControllerIdAccessLogs404Code;
};
