/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdAccessLogs200LogsItemStatus = typeof GetDoorsControllerIdAccessLogs200LogsItemStatus[keyof typeof GetDoorsControllerIdAccessLogs200LogsItemStatus];


export const GetDoorsControllerIdAccessLogs200LogsItemStatus = {
  GRANTED: 'GRANTED',
  DENIED: 'DENIED',
} as const;
