/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdCommands200CommandsItemStatus = typeof GetDoorsControllerIdCommands200CommandsItemStatus[keyof typeof GetDoorsControllerIdCommands200CommandsItemStatus];


export const GetDoorsControllerIdCommands200CommandsItemStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;
