/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetDoors200ControllersItem } from './getDoors200ControllersItem';

export type GetDoors200 = {
  controllers: GetDoors200ControllersItem[];
};
