/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetDoorsControllerIdCommands404Code = typeof GetDoorsControllerIdCommands404Code[keyof typeof GetDoorsControllerIdCommands404Code];


export const GetDoorsControllerIdCommands404Code = {
  CONTROLLER_NOT_FOUND: 'CONTROLLER_NOT_FOUND',
} as const;
