/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIotDevicesControllerIdCommands200CommandsItem } from './getIotDevicesControllerIdCommands200CommandsItem';

export type GetIotDevicesControllerIdCommands200 = {
  commands: GetIotDevicesControllerIdCommands200CommandsItem[];
};
