/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetLogs200ItemsItemCredentialType = typeof GetLogs200ItemsItemCredentialType[keyof typeof GetLogs200ItemsItemCredentialType] | null;


export const GetLogs200ItemsItemCredentialType = {
  FINGERPRINT: 'FINGERPRINT',
  NFC_TAG: 'NFC_TAG',
} as const;
