/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetLogs200ItemsItem } from './getLogs200ItemsItem';

export type GetLogs200 = {
  items: GetLogs200ItemsItem[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
};
