/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetLogs200ItemsItemStatus = typeof GetLogs200ItemsItemStatus[keyof typeof GetLogs200ItemsItemStatus];


export const GetLogs200ItemsItemStatus = {
  GRANTED: 'GRANTED',
  DENIED: 'DENIED',
} as const;
