/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetRooms200ResultItemRoomDoorState = typeof GetRooms200ResultItemRoomDoorState[keyof typeof GetRooms200ResultItemRoomDoorState];


export const GetRooms200ResultItemRoomDoorState = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  UNKNOWN: 'UNKNOWN',
} as const;
