/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetRooms200ResultItem } from './getRooms200ResultItem';

export type GetRooms200 = {
  result: GetRooms200ResultItem[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
};
