/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type GetRoomsParams = {
/**
 * Filtrar por nome da sala
 */
q?: string;
/**
 * IDs de tipos separados por vírgula
 */
typeIds?: string;
/**
 * IDs de blocos separados por vírgula
 */
blockIds?: string;
/**
 * @minimum 1
 * @maximum 9007199254740991
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
pageSize?: number;
};
