/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetRooms200ResultItemBlock } from './getRooms200ResultItemBlock';
import type { GetRooms200ResultItemRoom } from './getRooms200ResultItemRoom';

export type GetRooms200ResultItem = {
  room: GetRooms200ResultItemRoom;
  block: GetRooms200ResultItemBlock;
};
