/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoomsSummaryState } from './getRoomsSummaryState';

export type GetRoomsSummaryParams = {
/**
 * Filtro de busca por nome da sala, bloco ou (para admin) usuário
 */
q?: string;
/**
 * Filtrar por abreviação do tipo de sala
 */
type?: string;
/**
 * Filtrar por estado da porta
 */
state?: GetRoomsSummaryState;
};
