/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoomsIdRelations200ProfilesItem } from './getRoomsIdRelations200ProfilesItem';
import type { GetRoomsIdRelations200UsersItem } from './getRoomsIdRelations200UsersItem';

export type GetRoomsIdRelations200 = {
  profiles: GetRoomsIdRelations200ProfilesItem[];
  users: GetRoomsIdRelations200UsersItem[];
};
