/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersIdRelations200ProfilesItem } from './getUsersIdRelations200ProfilesItem';
import type { GetUsersIdRelations200RoomsItem } from './getUsersIdRelations200RoomsItem';
import type { GetUsersIdRelations200RoomTypesItem } from './getUsersIdRelations200RoomTypesItem';

export type GetUsersIdRelations200 = {
  profiles: GetUsersIdRelations200ProfilesItem[];
  rooms: GetUsersIdRelations200RoomsItem[];
  roomTypes: GetUsersIdRelations200RoomTypesItem[];
};
