/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PatchIotDevicesControllerIdCommandsCommandIdAck404Error = typeof PatchIotDevicesControllerIdCommandsCommandIdAck404Error[keyof typeof PatchIotDevicesControllerIdCommandsCommandIdAck404Error];


export const PatchIotDevicesControllerIdCommandsCommandIdAck404Error = {
  Command_not_found: 'Command not found',
} as const;
