/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PatchIotDevicesControllerIdCommandsCommandIdAck404Code = typeof PatchIotDevicesControllerIdCommandsCommandIdAck404Code[keyof typeof PatchIotDevicesControllerIdCommandsCommandIdAck404Code];


export const PatchIotDevicesControllerIdCommandsCommandIdAck404Code = {
  COMMAND_NOT_FOUND: 'COMMAND_NOT_FOUND',
} as const;
