/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchIotDevicesControllerIdCommandsCommandIdAck404Code } from './patchIotDevicesControllerIdCommandsCommandIdAck404Code';
import type { PatchIotDevicesControllerIdCommandsCommandIdAck404Error } from './patchIotDevicesControllerIdCommandsCommandIdAck404Error';

export type PatchIotDevicesControllerIdCommandsCommandIdAck404 = {
  error: PatchIotDevicesControllerIdCommandsCommandIdAck404Error;
  code: PatchIotDevicesControllerIdCommandsCommandIdAck404Code;
};
