/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchIotDevicesControllerIdHeartbeat404Code } from './patchIotDevicesControllerIdHeartbeat404Code';
import type { PatchIotDevicesControllerIdHeartbeat404Error } from './patchIotDevicesControllerIdHeartbeat404Error';

export type PatchIotDevicesControllerIdHeartbeat404 = {
  error: PatchIotDevicesControllerIdHeartbeat404Error;
  code: PatchIotDevicesControllerIdHeartbeat404Code;
};
