/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchIotDevicesControllerIdCommandsCommandIdAck200Command } from './patchIotDevicesControllerIdCommandsCommandIdAck200Command';

export type PatchIotDevicesControllerIdCommandsCommandIdAck200 = {
  command: PatchIotDevicesControllerIdCommandsCommandIdAck200Command;
};
