/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PatchIotDevicesControllerIdHeartbeat404Error = typeof PatchIotDevicesControllerIdHeartbeat404Error[keyof typeof PatchIotDevicesControllerIdHeartbeat404Error];


export const PatchIotDevicesControllerIdHeartbeat404Error = {
  Controller_not_registered: 'Controller not registered',
} as const;
