/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PatchIotDevicesControllerIdHeartbeat404Code = typeof PatchIotDevicesControllerIdHeartbeat404Code[keyof typeof PatchIotDevicesControllerIdHeartbeat404Code];


export const PatchIotDevicesControllerIdHeartbeat404Code = {
  CONTROLLER_NOT_FOUND: 'CONTROLLER_NOT_FOUND',
} as const;
