/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIotDevicesControllerIdAccessAttempts200Room } from './postIotDevicesControllerIdAccessAttempts200Room';
import type { PostIotDevicesControllerIdAccessAttempts200Status } from './postIotDevicesControllerIdAccessAttempts200Status';
import type { PostIotDevicesControllerIdAccessAttempts200User } from './postIotDevicesControllerIdAccessAttempts200User';

export type PostIotDevicesControllerIdAccessAttempts200 = {
  status: PostIotDevicesControllerIdAccessAttempts200Status;
  /** @nullable */
  reason: string | null;
  user?: PostIotDevicesControllerIdAccessAttempts200User;
  room?: PostIotDevicesControllerIdAccessAttempts200Room;
  requestId?: string;
};
