/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIotDevicesControllerIdAccessAttemptsBodyCredentialType } from './postIotDevicesControllerIdAccessAttemptsBodyCredentialType';

export type PostIotDevicesControllerIdAccessAttemptsBody = {
  credentialType: PostIotDevicesControllerIdAccessAttemptsBodyCredentialType;
  /** @minLength 1 */
  credentialValue: string;
  /** @minLength 1 */
  requestId?: string;
};
