/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIotDevicesControllerIdCommands201Command } from './postIotDevicesControllerIdCommands201Command';

export type PostIotDevicesControllerIdCommands201 = {
  command: PostIotDevicesControllerIdCommands201Command;
};
