/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PostDoorsControllerIdCommands404Error = typeof PostDoorsControllerIdCommands404Error[keyof typeof PostDoorsControllerIdCommands404Error];


export const PostDoorsControllerIdCommands404Error = {
  Controller_not_found: 'Controller not found',
} as const;
