/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PostIotDevicesControllerIdCommands201CommandStatus = typeof PostIotDevicesControllerIdCommands201CommandStatus[keyof typeof PostIotDevicesControllerIdCommands201CommandStatus];


export const PostIotDevicesControllerIdCommands201CommandStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;
