/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersIdFingerprints201Finger = typeof PostUsersIdFingerprints201Finger[keyof typeof PostUsersIdFingerprints201Finger];


export const PostUsersIdFingerprints201Finger = {
  right_thumb: 'right_thumb',
  right_index: 'right_index',
  right_middle: 'right_middle',
  right_ring: 'right_ring',
  right_pinky: 'right_pinky',
  left_thumb: 'left_thumb',
  left_index: 'left_index',
  left_middle: 'left_middle',
  left_ring: 'left_ring',
  left_pinky: 'left_pinky',
} as const;
