/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIotDevicesControllerIdCommandsBodyPayload } from './postIotDevicesControllerIdCommandsBodyPayload';
import type { PostIotDevicesControllerIdCommandsBodyType } from './postIotDevicesControllerIdCommandsBodyType';

export type PostIotDevicesControllerIdCommandsBody = {
  type: PostIotDevicesControllerIdCommandsBodyType;
  payload?: PostIotDevicesControllerIdCommandsBodyPayload;
  /** @maximum 9007199254740991 */
  expiresInSeconds?: number;
};
