/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostDoorsControllerIdCommandsBodyPayload } from './postDoorsControllerIdCommandsBodyPayload';
import type { PostDoorsControllerIdCommandsBodyType } from './postDoorsControllerIdCommandsBodyType';

export type PostDoorsControllerIdCommandsBody = {
  type: PostDoorsControllerIdCommandsBodyType;
  payload?: PostDoorsControllerIdCommandsBodyPayload;
  /** @maximum 9007199254740991 */
  expiresInSeconds?: number;
};
