/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PostIotDevicesControllerIdCommands201CommandType = typeof PostIotDevicesControllerIdCommands201CommandType[keyof typeof PostIotDevicesControllerIdCommands201CommandType];


export const PostIotDevicesControllerIdCommands201CommandType = {
  UNLOCK: 'UNLOCK',
  LOCK: 'LOCK',
  SYNC_STATE: 'SYNC_STATE',
} as const;
