/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostDoorsControllerIdCommands201Command } from './postDoorsControllerIdCommands201Command';

export type PostDoorsControllerIdCommands201 = {
  command: PostDoorsControllerIdCommands201Command;
};
