/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIotDevicesControllerIdEnrollmentBodyFinger } from './postIotDevicesControllerIdEnrollmentBodyFinger';

export type PostIotDevicesControllerIdEnrollmentBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  finger: PostIotDevicesControllerIdEnrollmentBodyFinger;
  /** @minLength 1 */
  template: string;
  /** @minLength 1 */
  enrollmentId?: string;
};
