/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PostDoorsControllerIdCommands404Code } from './postDoorsControllerIdCommands404Code';
import type { PostDoorsControllerIdCommands404Error } from './postDoorsControllerIdCommands404Error';

export type PostDoorsControllerIdCommands404 = {
  error: PostDoorsControllerIdCommands404Error;
  code: PostDoorsControllerIdCommands404Code;
};
