/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PostIotDevicesControllerIdAccessAttempts200Status = typeof PostIotDevicesControllerIdAccessAttempts200Status[keyof typeof PostIotDevicesControllerIdAccessAttempts200Status];


export const PostIotDevicesControllerIdAccessAttempts200Status = {
  GRANTED: 'GRANTED',
  DENIED: 'DENIED',
} as const;
