/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PutIotDevicesControllerIdStatus200Room } from './putIotDevicesControllerIdStatus200Room';

export type PutIotDevicesControllerIdStatus200 = {
  room: PutIotDevicesControllerIdStatus200Room;
};
