/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PutIotDevicesControllerIdBodySensorProtocol } from './putIotDevicesControllerIdBodySensorProtocol';

export type PutIotDevicesControllerIdBody = {
  /** @minLength 1 */
  roomId: string;
  /** @minLength 1 */
  firmwareVersion?: string;
  sensorProtocol?: PutIotDevicesControllerIdBodySensorProtocol;
  /** @minLength 1 */
  sensorModel?: string;
};
