/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PutIotDevicesControllerId200ControllerSensorProtocol = typeof PutIotDevicesControllerId200ControllerSensorProtocol[keyof typeof PutIotDevicesControllerId200ControllerSensorProtocol] | null;


export const PutIotDevicesControllerId200ControllerSensorProtocol = {
  R30X: 'R30X',
  BOLAND: 'BOLAND',
} as const;
