/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */

export type PutIotDevicesControllerIdStatus404Code = typeof PutIotDevicesControllerIdStatus404Code[keyof typeof PutIotDevicesControllerIdStatus404Code];


export const PutIotDevicesControllerIdStatus404Code = {
  CONTROLLER_NOT_FOUND: 'CONTROLLER_NOT_FOUND',
} as const;
