/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Access Control API
 * API REST para gerenciamento de usuários, salas e integrações IoT do sistema de controle de acesso.
 * OpenAPI spec version: 1.0.0
 */
import type { PutIotDevicesControllerIdStatus404Code } from './putIotDevicesControllerIdStatus404Code';
import type { PutIotDevicesControllerIdStatus404Error } from './putIotDevicesControllerIdStatus404Error';

export type PutIotDevicesControllerIdStatus404 = {
  error: PutIotDevicesControllerIdStatus404Error;
  code: PutIotDevicesControllerIdStatus404Code;
};
