name: CI - Web Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Clona o repositório para a máquina virtual.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Faz login no GitHub Container Registry (ghcr.io).
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Constrói e publica a imagem Docker.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/access-control-web:latest
            ghcr.io/${{ github.repository_owner }}/access-control-web:${{ github.sha }}